/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _BreachCutter from './BreachCutter.png';
import _BreachCutter_webp from './BreachCutter.png.webp';
import _DeepcoreGrenadeLauncher from './DeepcoreGrenadeLauncher.png';
import _DeepcoreGrenadeLauncher_webp from './DeepcoreGrenadeLauncher.png.webp';
import _StubbyVoltaicSMG from './StubbyVoltaicSMG.png';
import _StubbyVoltaicSMG_webp from './StubbyVoltaicSMG.png.webp';
import _WarthogShotgun from './WarthogShotgun.png';
import _WarthogShotgun_webp from './WarthogShotgun.png.webp';
export const BreachCutter = { png: _BreachCutter, webp: _BreachCutter_webp };
export const DeepcoreGrenadeLauncher = {
  png: _DeepcoreGrenadeLauncher,
  webp: _DeepcoreGrenadeLauncher_webp,
};
export const StubbyVoltaicSMG = {
  png: _StubbyVoltaicSMG,
  webp: _StubbyVoltaicSMG_webp,
};
export const WarthogShotgun = {
  png: _WarthogShotgun,
  webp: _WarthogShotgun_webp,
};
