/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _Barbaric from './Barbaric.png';
import _Barbaric_webp from './Barbaric.png.webp';
import _BlisterBot from './BlisterBot.png';
import _BlisterBot_webp from './BlisterBot.png.webp';
import _Bosco from './Bosco.png';
import _Bosco_webp from './Bosco.png.webp';
import _Icy from './Icy.png';
import _Icy_webp from './Icy.png.webp';
import _MossCrawler from './Moss_Crawler.png';
import _MossCrawler_webp from './Moss_Crawler.png.webp';
import _PlagueSplatter from './Plague_Splatter.png';
import _PlagueSplatter_webp from './Plague_Splatter.png.webp';
import _SurplusBarrel from './SurplusBarrel.png';
import _SurplusBarrel_webp from './SurplusBarrel.png.webp';
export const Barbaric = { png: _Barbaric, webp: _Barbaric_webp };
export const BlisterBot = { png: _BlisterBot, webp: _BlisterBot_webp };
export const Bosco = { png: _Bosco, webp: _Bosco_webp };
export const Icy = { png: _Icy, webp: _Icy_webp };
export const MossCrawler = { png: _MossCrawler, webp: _MossCrawler_webp };
export const PlagueSplatter = {
  png: _PlagueSplatter,
  webp: _PlagueSplatter_webp,
};
export const SurplusBarrel = { png: _SurplusBarrel, webp: _SurplusBarrel_webp };
