/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import * as AllClass from './AllClass';
import * as Driller from './Driller';
import * as Engineer from './Engineer';
import * as Gunner from './Gunner';
import * as Scout from './Scout';
const _imports = { AllClass, Driller, Engineer, Gunner, Scout };
export default _imports;
