/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _Bismor from './Bismor.png';
import _Bismor_webp from './Bismor.png.webp';
import _Credit from './Credit.png';
import _Credit_webp from './Credit.png.webp';
import _Croppa from './Croppa.png';
import _Croppa_webp from './Croppa.png.webp';
import _EnorPearl from './EnorPearl.png';
import _EnorPearl_webp from './EnorPearl.png.webp';
import _Jadiz from './Jadiz.png';
import _Jadiz_webp from './Jadiz.png.webp';
import _Magnite from './Magnite.png';
import _Magnite_webp from './Magnite.png.webp';
import _Umanite from './Umanite.png';
import _Umanite_webp from './Umanite.png.webp';
export const Bismor = { png: _Bismor, webp: _Bismor_webp };
export const Credit = { png: _Credit, webp: _Credit_webp };
export const Croppa = { png: _Croppa, webp: _Croppa_webp };
export const EnorPearl = { png: _EnorPearl, webp: _EnorPearl_webp };
export const Jadiz = { png: _Jadiz, webp: _Jadiz_webp };
export const Magnite = { png: _Magnite, webp: _Magnite_webp };
export const Umanite = { png: _Umanite, webp: _Umanite_webp };
