/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _Buff from './Buff.png';
import _Buff_webp from './Buff.png.webp';
import _Nerf from './Nerf.png';
import _Nerf_webp from './Nerf.png.webp';
export const Buff = { png: _Buff, webp: _Buff_webp };
export const Nerf = { png: _Nerf, webp: _Nerf_webp };
