/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import * as paintjobs from './paintjobs';
import * as skins from './skins';
import * as uniqueParts from './uniqueParts';
const _imports = { paintjobs, skins, uniqueParts };
export default _imports;
