/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import * as driller from './driller';
import * as engineer from './engineer';
import * as gunner from './gunner';
import * as scout from './scout';
const _imports = { driller, engineer, gunner, scout };
export default _imports;
