/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _BlackCrag from './Black_Crag.png';
import _BlackCrag_webp from './Black_Crag.png.webp';
import _BootCamp from './Boot_Camp.png';
import _BootCamp_webp from './Boot_Camp.png.webp';
import _DawnOfTheDread from './Dawn_of_the_Dread.png';
import _DawnOfTheDread_webp from './Dawn_of_the_Dread.png.webp';
import _MegaCorp from './MegaCorp.png';
import _MegaCorp_webp from './MegaCorp.png.webp';
import _RegalAegis from './Regal_Aegis.png';
import _RegalAegis_webp from './Regal_Aegis.png.webp';
import _Roughneck from './Roughneck.png';
import _Roughneck_webp from './Roughneck.png.webp';
import _ScaleBrigade from './Scale_Brigade.png';
import _ScaleBrigade_webp from './Scale_Brigade.png.webp';
import _ToxicDefender from './Toxic_Defender.png';
import _ToxicDefender_webp from './Toxic_Defender.png.webp';
export const BlackCrag = { png: _BlackCrag, webp: _BlackCrag_webp };
export const BootCamp = { png: _BootCamp, webp: _BootCamp_webp };
export const DawnOfTheDread = {
  png: _DawnOfTheDread,
  webp: _DawnOfTheDread_webp,
};
export const MegaCorp = { png: _MegaCorp, webp: _MegaCorp_webp };
export const RegalAegis = { png: _RegalAegis, webp: _RegalAegis_webp };
export const Roughneck = { png: _Roughneck, webp: _Roughneck_webp };
export const ScaleBrigade = { png: _ScaleBrigade, webp: _ScaleBrigade_webp };
export const ToxicDefender = { png: _ToxicDefender, webp: _ToxicDefender_webp };
