/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _BugHide from './bugHide.png';
import _BugHide_webp from './bugHide.png.webp';
import _CarvenPride from './carvenPride.png';
import _CarvenPride_webp from './carvenPride.png.webp';
import _ChasmBorneCliffhanger from './chasmBorneCliffhanger.png';
import _ChasmBorneCliffhanger_webp from './chasmBorneCliffhanger.png.webp';
import _CompanyStandard from './companyStandard.png';
import _CompanyStandard_webp from './companyStandard.png.webp';
import _DawnOfTheDread from './dawnOfTheDread.png';
import _DawnOfTheDread_webp from './dawnOfTheDread.png.webp';
import _DriftCrusher from './driftCrusher.png';
import _DriftCrusher_webp from './driftCrusher.png.webp';
import _GadgeteersFavorite from './gadgeteersFavorite.png';
import _GadgeteersFavorite_webp from './gadgeteersFavorite.png.webp';
import _Hammerblow from './hammerblow.png';
import _Hammerblow_webp from './hammerblow.png.webp';
import _Incorruptible from './incorruptible.png';
import _Incorruptible_webp from './incorruptible.png.webp';
import _JaggedSon from './jaggedSon.png';
import _JaggedSon_webp from './jaggedSon.png.webp';
import _MegaCorp from './megaCorp.png';
import _MegaCorp_webp from './megaCorp.png.webp';
import _Pneumatic from './pneumatic.png';
import _Pneumatic_webp from './pneumatic.png.webp';
import _ReapersClaw from './reapersClaw.png';
import _ReapersClaw_webp from './reapersClaw.png.webp';
import _Roughneck from './roughneck.png';
import _Roughneck_webp from './roughneck.png.webp';
import _TheSupporter from './theSupporter.png';
import _TheSupporter_webp from './theSupporter.png.webp';
export const BugHide = { png: _BugHide, webp: _BugHide_webp };
export const CarvenPride = { png: _CarvenPride, webp: _CarvenPride_webp };
export const ChasmBorneCliffhanger = {
  png: _ChasmBorneCliffhanger,
  webp: _ChasmBorneCliffhanger_webp,
};
export const CompanyStandard = {
  png: _CompanyStandard,
  webp: _CompanyStandard_webp,
};
export const DawnOfTheDread = {
  png: _DawnOfTheDread,
  webp: _DawnOfTheDread_webp,
};
export const DriftCrusher = { png: _DriftCrusher, webp: _DriftCrusher_webp };
export const GadgeteersFavorite = {
  png: _GadgeteersFavorite,
  webp: _GadgeteersFavorite_webp,
};
export const Hammerblow = { png: _Hammerblow, webp: _Hammerblow_webp };
export const Incorruptible = { png: _Incorruptible, webp: _Incorruptible_webp };
export const JaggedSon = { png: _JaggedSon, webp: _JaggedSon_webp };
export const MegaCorp = { png: _MegaCorp, webp: _MegaCorp_webp };
export const Pneumatic = { png: _Pneumatic, webp: _Pneumatic_webp };
export const ReapersClaw = { png: _ReapersClaw, webp: _ReapersClaw_webp };
export const Roughneck = { png: _Roughneck, webp: _Roughneck_webp };
export const TheSupporter = { png: _TheSupporter, webp: _TheSupporter_webp };
