/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _DrillerPortrait from './Driller_portrait.png';
import _DrillerPortrait_webp from './Driller_portrait.png.webp';
import _EngineerPortrait from './Engineer_portrait.png';
import _EngineerPortrait_webp from './Engineer_portrait.png.webp';
import _GunnerPortrait from './Gunner_portrait.png';
import _GunnerPortrait_webp from './Gunner_portrait.png.webp';
import _MissionControlPortrait from './Mission_control_portrait.png';
import _MissionControlPortrait_webp from './Mission_control_portrait.png.webp';
import _ScoutPortrait from './Scout_portrait.png';
import _ScoutPortrait_webp from './Scout_portrait.png.webp';
export const DrillerPortrait = {
  png: _DrillerPortrait,
  webp: _DrillerPortrait_webp,
};
export const EngineerPortrait = {
  png: _EngineerPortrait,
  webp: _EngineerPortrait_webp,
};
export const GunnerPortrait = {
  png: _GunnerPortrait,
  webp: _GunnerPortrait_webp,
};
export const MissionControlPortrait = {
  png: _MissionControlPortrait,
  webp: _MissionControlPortrait_webp,
};
export const ScoutPortrait = { png: _ScoutPortrait, webp: _ScoutPortrait_webp };
