/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import * as arrows from './arrows';
import * as frames from './frames';
import * as icons from './icons';
const _imports = { arrows, frames, icons };
export default _imports;
