/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _BeerToss from './Beer_Toss.jpg';
import _BeerToss_webp from './Beer_Toss.jpg.webp';
import _BarrelDrop from './barrel_drop.png';
import _BarrelDrop_webp from './barrel_drop.png.webp';
import _ClassicFlex from './classic_flex.png';
import _ClassicFlex_webp from './classic_flex.png.webp';
import _CrowdPleaser from './crowd_pleaser.png';
import _CrowdPleaser_webp from './crowd_pleaser.png.webp';
import _CrystalLover from './crystal_lover.png';
import _CrystalLover_webp from './crystal_lover.png.webp';
import _DualDrinkDrop from './dual_drink_drop.png';
import _DualDrinkDrop_webp from './dual_drink_drop.png.webp';
import _Fingerguns from './fingerguns.png';
import _Fingerguns_webp from './fingerguns.png.webp';
import _FlexThemGuns from './flex_them_guns.png';
import _FlexThemGuns_webp from './flex_them_guns.png.webp';
import _FuriousClown from './furious_clown.png';
import _FuriousClown_webp from './furious_clown.png.webp';
import _Handstand from './handstand.png';
import _Handstand_webp from './handstand.png.webp';
import _PraiseMe from './praise_me.png';
import _PraiseMe_webp from './praise_me.png.webp';
import _SharpSalute from './sharp_salute.png';
import _SharpSalute_webp from './sharp_salute.png.webp';
import _Smooches from './smooches.png';
import _Smooches_webp from './smooches.png.webp';
import _SmugPushups from './smug_pushups.png';
import _SmugPushups_webp from './smug_pushups.png.webp';
import _SwarmerInfestation from './swarmer_infestation.png';
import _SwarmerInfestation_webp from './swarmer_infestation.png.webp';
import _SwarmerKick from './swarmer_kick.png';
import _SwarmerKick_webp from './swarmer_kick.png.webp';
import _SwarmerStomp from './swarmer_stomp.png';
import _SwarmerStomp_webp from './swarmer_stomp.png.webp';
import _TheatricalBow from './theatrical_bow.png';
import _TheatricalBow_webp from './theatrical_bow.png.webp';
import _ThreePointLanding from './three_point_landing.png';
import _ThreePointLanding_webp from './three_point_landing.png.webp';
export const BarrelDrop = { png: _BarrelDrop, webp: _BarrelDrop_webp };
export const ClassicFlex = { png: _ClassicFlex, webp: _ClassicFlex_webp };
export const CrowdPleaser = { png: _CrowdPleaser, webp: _CrowdPleaser_webp };
export const CrystalLover = { png: _CrystalLover, webp: _CrystalLover_webp };
export const DualDrinkDrop = { png: _DualDrinkDrop, webp: _DualDrinkDrop_webp };
export const Fingerguns = { png: _Fingerguns, webp: _Fingerguns_webp };
export const FlexThemGuns = { png: _FlexThemGuns, webp: _FlexThemGuns_webp };
export const FuriousClown = { png: _FuriousClown, webp: _FuriousClown_webp };
export const Handstand = { png: _Handstand, webp: _Handstand_webp };
export const PraiseMe = { png: _PraiseMe, webp: _PraiseMe_webp };
export const SharpSalute = { png: _SharpSalute, webp: _SharpSalute_webp };
export const Smooches = { png: _Smooches, webp: _Smooches_webp };
export const SmugPushups = { png: _SmugPushups, webp: _SmugPushups_webp };
export const SwarmerInfestation = {
  png: _SwarmerInfestation,
  webp: _SwarmerInfestation_webp,
};
export const SwarmerKick = { png: _SwarmerKick, webp: _SwarmerKick_webp };
export const SwarmerStomp = { png: _SwarmerStomp, webp: _SwarmerStomp_webp };
export const TheatricalBow = { png: _TheatricalBow, webp: _TheatricalBow_webp };
export const ThreePointLanding = {
  png: _ThreePointLanding,
  webp: _ThreePointLanding_webp,
};
export const BeerToss = { jpg: _BeerToss, webp: _BeerToss_webp };
