/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _BarrelDrop from './Barrel_Drop.png';
import _BarrelDrop_webp from './Barrel_Drop.png.webp';
import _BeerToss from './Beer_Toss.png';
import _BeerToss_webp from './Beer_Toss.png.webp';
import _Boxer from './Boxer.png';
import _Boxer_webp from './Boxer.png.webp';
import _ChestThumper from './Chest_Thumper.png';
import _ChestThumper_webp from './Chest_Thumper.png.webp';
import _ClassicFlex from './Classic_Flex.png';
import _ClassicFlex_webp from './Classic_Flex.png.webp';
import _ConfettiCannon from './Confetti_Cannon.png';
import _ConfettiCannon_webp from './Confetti_Cannon.png.webp';
import _CrowdPleaser from './Crowd_Pleaser.png';
import _CrowdPleaser_webp from './Crowd_Pleaser.png.webp';
import _CrystalLover from './Crystal_Lover.png';
import _CrystalLover_webp from './Crystal_Lover.png.webp';
import _DualDrinkDrop from './Dual_Drink_Drop.png';
import _DualDrinkDrop_webp from './Dual_Drink_Drop.png.webp';
import _FeedingLootbug from './Feeding_Lootbug.png';
import _FeedingLootbug_webp from './Feeding_Lootbug.png.webp';
import _Fingerguns from './Fingerguns.png';
import _Fingerguns_webp from './Fingerguns.png.webp';
import _FlexThemGuns from './Flex_Them_Guns.png';
import _FlexThemGuns_webp from './Flex_Them_Guns.png.webp';
import _FuriousClown from './Furious_Clown.png';
import _FuriousClown_webp from './Furious_Clown.png.webp';
import _Handstand from './Handstand.png';
import _Handstand_webp from './Handstand.png.webp';
import _Juggle from './Juggle.png';
import _Juggle_webp from './Juggle.png.webp';
import _Knight from './Knight.png';
import _Knight_webp from './Knight.png.webp';
import _LootbugLover from './Lootbug_Lover.png';
import _LootbugLover_webp from './Lootbug_Lover.png.webp';
import _PickaxeThrow from './Pickaxe_Throw.png';
import _PickaxeThrow_webp from './Pickaxe_Throw.png.webp';
import _PraiseMe from './Praise_Me.png';
import _PraiseMe_webp from './Praise_Me.png.webp';
import _ProudFist from './Proud_Fist.png';
import _ProudFist_webp from './Proud_Fist.png.webp';
import _Salt from './Salt.png';
import _Salt_webp from './Salt.png.webp';
import _SatisfiedApplause from './Satisfied_Applause.png';
import _SatisfiedApplause_webp from './Satisfied_Applause.png.webp';
import _SharpSalute from './Sharp_Salute.png';
import _SharpSalute_webp from './Sharp_Salute.png.webp';
import _Smooches from './Smooches.png';
import _Smooches_webp from './Smooches.png.webp';
import _SmugPushups from './Smug_Pushups.png';
import _SmugPushups_webp from './Smug_Pushups.png.webp';
import _Strongman from './Strongman.png';
import _Strongman_webp from './Strongman.png.webp';
import _SwarmerInfestation from './Swarmer_Infestation.png';
import _SwarmerInfestation_webp from './Swarmer_Infestation.png.webp';
import _SwarmerKick from './Swarmer_Kick.png';
import _SwarmerKick_webp from './Swarmer_Kick.png.webp';
import _SwarmerStomp from './Swarmer_Stomp.png';
import _SwarmerStomp_webp from './Swarmer_Stomp.png.webp';
import _TheatricalBow from './Theatrical_Bow.png';
import _TheatricalBow_webp from './Theatrical_Bow.png.webp';
import _ThreePointLanding from './Three_Point_Landing.png';
import _ThreePointLanding_webp from './Three_Point_Landing.png.webp';
export const BarrelDrop = { png: _BarrelDrop, webp: _BarrelDrop_webp };
export const BeerToss = { png: _BeerToss, webp: _BeerToss_webp };
export const Boxer = { png: _Boxer, webp: _Boxer_webp };
export const ChestThumper = { png: _ChestThumper, webp: _ChestThumper_webp };
export const ClassicFlex = { png: _ClassicFlex, webp: _ClassicFlex_webp };
export const ConfettiCannon = {
  png: _ConfettiCannon,
  webp: _ConfettiCannon_webp,
};
export const CrowdPleaser = { png: _CrowdPleaser, webp: _CrowdPleaser_webp };
export const CrystalLover = { png: _CrystalLover, webp: _CrystalLover_webp };
export const DualDrinkDrop = { png: _DualDrinkDrop, webp: _DualDrinkDrop_webp };
export const FeedingLootbug = {
  png: _FeedingLootbug,
  webp: _FeedingLootbug_webp,
};
export const Fingerguns = { png: _Fingerguns, webp: _Fingerguns_webp };
export const FlexThemGuns = { png: _FlexThemGuns, webp: _FlexThemGuns_webp };
export const FuriousClown = { png: _FuriousClown, webp: _FuriousClown_webp };
export const Handstand = { png: _Handstand, webp: _Handstand_webp };
export const Juggle = { png: _Juggle, webp: _Juggle_webp };
export const Knight = { png: _Knight, webp: _Knight_webp };
export const LootbugLover = { png: _LootbugLover, webp: _LootbugLover_webp };
export const PickaxeThrow = { png: _PickaxeThrow, webp: _PickaxeThrow_webp };
export const PraiseMe = { png: _PraiseMe, webp: _PraiseMe_webp };
export const ProudFist = { png: _ProudFist, webp: _ProudFist_webp };
export const Salt = { png: _Salt, webp: _Salt_webp };
export const SatisfiedApplause = {
  png: _SatisfiedApplause,
  webp: _SatisfiedApplause_webp,
};
export const SharpSalute = { png: _SharpSalute, webp: _SharpSalute_webp };
export const Smooches = { png: _Smooches, webp: _Smooches_webp };
export const SmugPushups = { png: _SmugPushups, webp: _SmugPushups_webp };
export const Strongman = { png: _Strongman, webp: _Strongman_webp };
export const SwarmerInfestation = {
  png: _SwarmerInfestation,
  webp: _SwarmerInfestation_webp,
};
export const SwarmerKick = { png: _SwarmerKick, webp: _SwarmerKick_webp };
export const SwarmerStomp = { png: _SwarmerStomp, webp: _SwarmerStomp_webp };
export const TheatricalBow = { png: _TheatricalBow, webp: _TheatricalBow_webp };
export const ThreePointLanding = {
  png: _ThreePointLanding,
  webp: _ThreePointLanding_webp,
};
