/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _AcidWash from './Acid_Wash.png';
import _AcidWash_webp from './Acid_Wash.png.webp';
import _BeyondTheCircuit from './Beyond_The_Circuit.png';
import _BeyondTheCircuit_webp from './Beyond_The_Circuit.png.webp';
import _Biohazard from './Biohazard.png';
import _Biohazard_webp from './Biohazard.png.webp';
import _BootCamp from './Boot_Camp.png';
import _BootCamp_webp from './Boot_Camp.png.webp';
import _CopperPatinate from './Copper_Patinate.png';
import _CopperPatinate_webp from './Copper_Patinate.png.webp';
import _DarkDescent from './Dark_Descent.png';
import _DarkDescent_webp from './Dark_Descent.png.webp';
import _DarkFuture from './Dark_Future.png';
import _DarkFuture_webp from './Dark_Future.png.webp';
import _DawnOfTheDread from './Dawn_of_the_Dread.png';
import _DawnOfTheDread_webp from './Dawn_of_the_Dread.png.webp';
import _DeepSeaDefender from './Deep_Sea_Defender.png';
import _DeepSeaDefender_webp from './Deep_Sea_Defender.png.webp';
import _Deepcore from './Deepcore.png';
import _Deepcore_webp from './Deepcore.png.webp';
import _DesertRanger from './Desert_Ranger.png';
import _DesertRanger_webp from './Desert_Ranger.png.webp';
import _DigitalDanger from './Digital_Danger.png';
import _DigitalDanger_webp from './Digital_Danger.png.webp';
import _Fiery from './Fiery.png';
import _Fiery_webp from './Fiery.png.webp';
import _FirstStripe from './First_Stripe.png';
import _FirstStripe_webp from './First_Stripe.png.webp';
import _GhostlyPale from './Ghostly_Pale.png';
import _GhostlyPale_webp from './Ghostly_Pale.png.webp';
import _GoldenMauve from './Golden_Mauve.png';
import _GoldenMauve_webp from './Golden_Mauve.png.webp';
import _JungleRaid from './Jungle_Raid.png';
import _JungleRaid_webp from './Jungle_Raid.png.webp';
import _MegaCorp from './MegaCorp.png';
import _MegaCorp_webp from './MegaCorp.png.webp';
import _MetallicVintage from './Metallic_Vintage.png';
import _MetallicVintage_webp from './Metallic_Vintage.png.webp';
import _MintAssault from './Mint_Assault.png';
import _MintAssault_webp from './Mint_Assault.png.webp';
import _MossCrawler from './Moss_Crawler.png';
import _MossCrawler_webp from './Moss_Crawler.png.webp';
import _Predator from './Predator.png';
import _Predator_webp from './Predator.png.webp';
import _PrimalBlood from './Primal_Blood.png';
import _PrimalBlood_webp from './Primal_Blood.png.webp';
import _RivalTech from './Rival_Tech.png';
import _RivalTech_webp from './Rival_Tech.png.webp';
import _RobotRebellion from './Robot_Rebellion.png';
import _RobotRebellion_webp from './Robot_Rebellion.png.webp';
import _Roughneck from './Roughneck.png';
import _Roughneck_webp from './Roughneck.png.webp';
import _SaltCrystal from './Salt_Crystal.png';
import _SaltCrystal_webp from './Salt_Crystal.png.webp';
import _ScratchedMetal from './Scratched_Metal.png';
import _ScratchedMetal_webp from './Scratched_Metal.png.webp';
import _Sleek from './Sleek.png';
import _Sleek_webp from './Sleek.png.webp';
import _TheCompanySpecial from './The_Company_Special.png';
import _TheCompanySpecial_webp from './The_Company_Special.png.webp';
import _TheSupporter from './The_Supporter.png';
import _TheSupporter_webp from './The_Supporter.png.webp';
import _ToolOfDestruction from './Tool_Of_Destruction.png';
import _ToolOfDestruction_webp from './Tool_Of_Destruction.png.webp';
import _TrustyRusty from './Trusty_Rusty.png';
import _TrustyRusty_webp from './Trusty_Rusty.png.webp';
import _Warmonger from './Warmonger.png';
import _Warmonger_webp from './Warmonger.png.webp';
export const AcidWash = { png: _AcidWash, webp: _AcidWash_webp };
export const BeyondTheCircuit = {
  png: _BeyondTheCircuit,
  webp: _BeyondTheCircuit_webp,
};
export const Biohazard = { png: _Biohazard, webp: _Biohazard_webp };
export const BootCamp = { png: _BootCamp, webp: _BootCamp_webp };
export const CopperPatinate = {
  png: _CopperPatinate,
  webp: _CopperPatinate_webp,
};
export const DarkDescent = { png: _DarkDescent, webp: _DarkDescent_webp };
export const DarkFuture = { png: _DarkFuture, webp: _DarkFuture_webp };
export const DawnOfTheDread = {
  png: _DawnOfTheDread,
  webp: _DawnOfTheDread_webp,
};
export const Deepcore = { png: _Deepcore, webp: _Deepcore_webp };
export const DeepSeaDefender = {
  png: _DeepSeaDefender,
  webp: _DeepSeaDefender_webp,
};
export const DesertRanger = { png: _DesertRanger, webp: _DesertRanger_webp };
export const DigitalDanger = { png: _DigitalDanger, webp: _DigitalDanger_webp };
export const Fiery = { png: _Fiery, webp: _Fiery_webp };
export const FirstStripe = { png: _FirstStripe, webp: _FirstStripe_webp };
export const GhostlyPale = { png: _GhostlyPale, webp: _GhostlyPale_webp };
export const GoldenMauve = { png: _GoldenMauve, webp: _GoldenMauve_webp };
export const JungleRaid = { png: _JungleRaid, webp: _JungleRaid_webp };
export const MegaCorp = { png: _MegaCorp, webp: _MegaCorp_webp };
export const MetallicVintage = {
  png: _MetallicVintage,
  webp: _MetallicVintage_webp,
};
export const MintAssault = { png: _MintAssault, webp: _MintAssault_webp };
export const MossCrawler = { png: _MossCrawler, webp: _MossCrawler_webp };
export const Predator = { png: _Predator, webp: _Predator_webp };
export const PrimalBlood = { png: _PrimalBlood, webp: _PrimalBlood_webp };
export const RivalTech = { png: _RivalTech, webp: _RivalTech_webp };
export const RobotRebellion = {
  png: _RobotRebellion,
  webp: _RobotRebellion_webp,
};
export const Roughneck = { png: _Roughneck, webp: _Roughneck_webp };
export const SaltCrystal = { png: _SaltCrystal, webp: _SaltCrystal_webp };
export const ScratchedMetal = {
  png: _ScratchedMetal,
  webp: _ScratchedMetal_webp,
};
export const Sleek = { png: _Sleek, webp: _Sleek_webp };
export const TheCompanySpecial = {
  png: _TheCompanySpecial,
  webp: _TheCompanySpecial_webp,
};
export const TheSupporter = { png: _TheSupporter, webp: _TheSupporter_webp };
export const ToolOfDestruction = {
  png: _ToolOfDestruction,
  webp: _ToolOfDestruction_webp,
};
export const TrustyRusty = { png: _TrustyRusty, webp: _TrustyRusty_webp };
export const Warmonger = { png: _Warmonger, webp: _Warmonger_webp };
