/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _CustomEngineered from './Custom_Engineered.png';
import _CustomEngineered_webp from './Custom_Engineered.png.webp';
import _FourthRelic from './Fourth_Relic.png';
import _FourthRelic_webp from './Fourth_Relic.png.webp';
import _GlyphidTrophyHunter from './Glyphid_Trophy_Hunter.png';
import _GlyphidTrophyHunter_webp from './Glyphid_Trophy_Hunter.png.webp';
import _Mechanized from './Mechanized.png';
import _Mechanized_webp from './Mechanized.png.webp';
import _NeonBand from './Neon_Band.png';
import _NeonBand_webp from './Neon_Band.png.webp';
import _ScaleBrigade from './Scale_Brigade.png';
import _ScaleBrigade_webp from './Scale_Brigade.png.webp';
export const CustomEngineered = {
  png: _CustomEngineered,
  webp: _CustomEngineered_webp,
};
export const FourthRelic = { png: _FourthRelic, webp: _FourthRelic_webp };
export const GlyphidTrophyHunter = {
  png: _GlyphidTrophyHunter,
  webp: _GlyphidTrophyHunter_webp,
};
export const Mechanized = { png: _Mechanized, webp: _Mechanized_webp };
export const NeonBand = { png: _NeonBand, webp: _NeonBand_webp };
export const ScaleBrigade = { png: _ScaleBrigade, webp: _ScaleBrigade_webp };
