/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import * as images from './images';
import * as outlines from './outlines';
const _imports = { images, outlines };
export default _imports;
