/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _AquaForce from './Aqua_Force.png';
import _AquaForce_webp from './Aqua_Force.png.webp';
import _AzureDraft from './Azure_Draft.png';
import _AzureDraft_webp from './Azure_Draft.png.webp';
import _DarkStripes from './Dark_Stripes.png';
import _DarkStripes_webp from './Dark_Stripes.png.webp';
import _DustyWinds from './Dusty_Winds.png';
import _DustyWinds_webp from './Dusty_Winds.png.webp';
import _FrigidTiger from './Frigid_Tiger.png';
import _FrigidTiger_webp from './Frigid_Tiger.png.webp';
import _SDarkFuture from './S_Dark_Future.png';
import _SDarkFuture_webp from './S_Dark_Future.png.webp';
import _SDefaultPaintjob from './S_Default_Paintjob.png';
import _SDefaultPaintjob_webp from './S_Default_Paintjob.png.webp';
import _SSplattered from './S_Splattered.png';
import _SSplattered_webp from './S_Splattered.png.webp';
import _STheSupporter from './S_The_Supporter.png';
import _STheSupporter_webp from './S_The_Supporter.png.webp';
import _SubtleShadow from './Subtle_Shadow.png';
import _SubtleShadow_webp from './Subtle_Shadow.png.webp';
export const AquaForce = { png: _AquaForce, webp: _AquaForce_webp };
export const AzureDraft = { png: _AzureDraft, webp: _AzureDraft_webp };
export const DarkStripes = { png: _DarkStripes, webp: _DarkStripes_webp };
export const DustyWinds = { png: _DustyWinds, webp: _DustyWinds_webp };
export const FrigidTiger = { png: _FrigidTiger, webp: _FrigidTiger_webp };
export const SDarkFuture = { png: _SDarkFuture, webp: _SDarkFuture_webp };
export const SDefaultPaintjob = {
  png: _SDefaultPaintjob,
  webp: _SDefaultPaintjob_webp,
};
export const SSplattered = { png: _SSplattered, webp: _SSplattered_webp };
export const STheSupporter = { png: _STheSupporter, webp: _STheSupporter_webp };
export const SubtleShadow = { png: _SubtleShadow, webp: _SubtleShadow_webp };
