/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _BugHide from './bugHide.jpg';
import _BugHide_webp from './bugHide.jpg.webp';
import _CarvenPride from './carvenPride.jpg';
import _CarvenPride_webp from './carvenPride.jpg.webp';
import _ChasmBorneCliffhanger from './chasmBorneCliffhanger.jpg';
import _ChasmBorneCliffhanger_webp from './chasmBorneCliffhanger.jpg.webp';
import _CompanyStandard from './companyStandard.jpg';
import _CompanyStandard_webp from './companyStandard.jpg.webp';
import _DriftCrusher from './driftCrusher.jpg';
import _DriftCrusher_webp from './driftCrusher.jpg.webp';
import _GadgeteersFavorite from './gadgeteersFavorite.jpg';
import _GadgeteersFavorite_webp from './gadgeteersFavorite.jpg.webp';
import _Hammerblow from './hammerblow.jpg';
import _Hammerblow_webp from './hammerblow.jpg.webp';
import _Incorruptible from './incorruptible.jpg';
import _Incorruptible_webp from './incorruptible.jpg.webp';
import _JaggedSon from './jaggedSon.jpg';
import _JaggedSon_webp from './jaggedSon.jpg.webp';
import _Pneumatic from './pneumatic.jpg';
import _Pneumatic_webp from './pneumatic.jpg.webp';
import _ReapersClaw from './reapersClaw.jpg';
import _ReapersClaw_webp from './reapersClaw.jpg.webp';
export const BugHide = { jpg: _BugHide, webp: _BugHide_webp };
export const CarvenPride = { jpg: _CarvenPride, webp: _CarvenPride_webp };
export const ChasmBorneCliffhanger = {
  jpg: _ChasmBorneCliffhanger,
  webp: _ChasmBorneCliffhanger_webp,
};
export const CompanyStandard = {
  jpg: _CompanyStandard,
  webp: _CompanyStandard_webp,
};
export const DriftCrusher = { jpg: _DriftCrusher, webp: _DriftCrusher_webp };
export const GadgeteersFavorite = {
  jpg: _GadgeteersFavorite,
  webp: _GadgeteersFavorite_webp,
};
export const Hammerblow = { jpg: _Hammerblow, webp: _Hammerblow_webp };
export const Incorruptible = { jpg: _Incorruptible, webp: _Incorruptible_webp };
export const JaggedSon = { jpg: _JaggedSon, webp: _JaggedSon_webp };
export const Pneumatic = { jpg: _Pneumatic, webp: _Pneumatic_webp };
export const ReapersClaw = { jpg: _ReapersClaw, webp: _ReapersClaw_webp };
