/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _BangledBraids from './Bangled_Braids.png';
import _BangledBraids_webp from './Bangled_Braids.png.webp';
import _Berserker from './Berserker.png';
import _Berserker_webp from './Berserker.png.webp';
import _BigOlSwirls from './Big_Ol_Swirls.png';
import _BigOlSwirls_webp from './Big_Ol_Swirls.png.webp';
import _BikerHelmet from './Biker_Helmet.png';
import _BikerHelmet_webp from './Biker_Helmet.png.webp';
import _BoundBraids from './Bound_Braids.png';
import _BoundBraids_webp from './Bound_Braids.png.webp';
import _BoundGoatee from './Bound_Goatee.png';
import _BoundGoatee_webp from './Bound_Goatee.png.webp';
import _BoundGoateeArmored from './Bound_Goatee_Armored.png';
import _BoundGoateeArmored_webp from './Bound_Goatee_Armored.png.webp';
import _BoundGoateeGilded from './Bound_Goatee_Gilded.png';
import _BoundGoateeGilded_webp from './Bound_Goatee_Gilded.png.webp';
import _BoundUnicord from './Bound_Unicord.png';
import _BoundUnicord_webp from './Bound_Unicord.png.webp';
import _BoundUnicordArmored from './Bound_Unicord_Armored.png';
import _BoundUnicordArmored_webp from './Bound_Unicord_Armored.png.webp';
import _BoundUnicordGilded from './Bound_Unicord_Gilded.png';
import _BoundUnicordGilded_webp from './Bound_Unicord_Gilded.png.webp';
import _BraidedAbundance from './Braided_Abundance.png';
import _BraidedAbundance_webp from './Braided_Abundance.png.webp';
import _BraidedAbundanceArmored from './Braided_Abundance_Armored.png';
import _BraidedAbundanceArmored_webp from './Braided_Abundance_Armored.png.webp';
import _BraidedAbundanceGilded from './Braided_Abundance_Gilded.png';
import _BraidedAbundanceGilded_webp from './Braided_Abundance_Gilded.png.webp';
import _BraidedBangles from './Braided_Bangles.png';
import _BraidedBangles_webp from './Braided_Bangles.png.webp';
import _BraidedBoldness from './Braided_Boldness.png';
import _BraidedBoldness_webp from './Braided_Boldness.png.webp';
import _BushyGoodGuy from './Bushy_Good_Guy.png';
import _BushyGoodGuy_webp from './Bushy_Good_Guy.png.webp';
import _CategoryBeards from './Category_Beards.png';
import _CategoryBeards_webp from './Category_Beards.png.webp';
import _CategoryHeadwear from './Category_Headwear.png';
import _CategoryHeadwear_webp from './Category_Headwear.png.webp';
import _CategoryMoustaches from './Category_Moustaches.png';
import _CategoryMoustaches_webp from './Category_Moustaches.png.webp';
import _CategorySideburns from './Category_Sideburns.png';
import _CategorySideburns_webp from './Category_Sideburns.png.webp';
import _CrescentMoon from './Crescent_Moon.png';
import _CrescentMoon_webp from './Crescent_Moon.png.webp';
import _CrestedWaterfall from './Crested_Waterfall.png';
import _CrestedWaterfall_webp from './Crested_Waterfall.png.webp';
import _CurlyOptimist from './Curly_Optimist.png';
import _CurlyOptimist_webp from './Curly_Optimist.png.webp';
import _CyborgEye from './Cyborg_Eye.png';
import _CyborgEye_webp from './Cyborg_Eye.png.webp';
import _DandyHandlebar from './Dandy_Handlebar.png';
import _DandyHandlebar_webp from './Dandy_Handlebar.png.webp';
import _DoubleHorsetails from './Double_Horsetails.png';
import _DoubleHorsetails_webp from './Double_Horsetails.png.webp';
import _DoubleHorsetailsArmored from './Double_Horsetails_Armored.png';
import _DoubleHorsetailsArmored_webp from './Double_Horsetails_Armored.png.webp';
import _DoubleHorsetailsGilded from './Double_Horsetails_Gilded.png';
import _DoubleHorsetailsGilded_webp from './Double_Horsetails_Gilded.png.webp';
import _ExquisiteHandlebar from './Exquisite_Handlebar.png';
import _ExquisiteHandlebar_webp from './Exquisite_Handlebar.png.webp';
import _FirstBlood from './First_Blood.png';
import _FirstBlood_webp from './First_Blood.png.webp';
import _ForeheadGoggles from './Forehead_Goggles.png';
import _ForeheadGoggles_webp from './Forehead_Goggles.png.webp';
import _FullHeadwrap from './Full_Headwrap.png';
import _FullHeadwrap_webp from './Full_Headwrap.png.webp';
import _GeekChic from './Geek_Chic.png';
import _GeekChic_webp from './Geek_Chic.png.webp';
import _GemStuddedHeadcover from './Gem_Studded_Headcover.png';
import _GemStuddedHeadcover_webp from './Gem_Studded_Headcover.png.webp';
import _GoggledHeadwrap from './Goggled_Headwrap.png';
import _GoggledHeadwrap_webp from './Goggled_Headwrap.png.webp';
import _GreatFork from './Great_Fork.png';
import _GreatFork_webp from './Great_Fork.png.webp';
import _GreatForkArmored from './Great_Fork_Armored.png';
import _GreatForkArmored_webp from './Great_Fork_Armored.png.webp';
import _GreatForkGilded from './Great_Fork_Gilded.png';
import _GreatForkGilded_webp from './Great_Fork_Gilded.png.webp';
import _GrimSpecterFullFace from './Grim_Specter_Full_Face.png';
import _GrimSpecterFullFace_webp from './Grim_Specter_Full_Face.png.webp';
import _GrimSpecterHalfFace from './Grim_Specter_Half_Face.png';
import _GrimSpecterHalfFace_webp from './Grim_Specter_Half_Face.png.webp';
import _Heatwave from './Heatwave.png';
import _Heatwave_webp from './Heatwave.png.webp';
import _HexHelmet from './Hex_Helmet.png';
import _HexHelmet_webp from './Hex_Helmet.png.webp';
import _HockeyMask from './Hockey_Mask.png';
import _HockeyMask_webp from './Hockey_Mask.png.webp';
import _ImmenseDanglies from './Immense_Danglies.png';
import _ImmenseDanglies_webp from './Immense_Danglies.png.webp';
import _IndustrialFacemask from './Industrial_Facemask.png';
import _IndustrialFacemask_webp from './Industrial_Facemask.png.webp';
import _IronCyclops from './Iron_Cyclops.png';
import _IronCyclops_webp from './Iron_Cyclops.png.webp';
import _JovialMajesty from './Jovial_Majesty.png';
import _JovialMajesty_webp from './Jovial_Majesty.png.webp';
import _Lowrider from './Lowrider.png';
import _Lowrider_webp from './Lowrider.png.webp';
import _MagnificentRaider from './Magnificent_Raider.png';
import _MagnificentRaider_webp from './Magnificent_Raider.png.webp';
import _Marshall from './Marshall.png';
import _Marshall_webp from './Marshall.png.webp';
import _MassiveBraid from './Massive_Braid.png';
import _MassiveBraid_webp from './Massive_Braid.png.webp';
import _MassiveBraidArmored from './Massive_Braid_Armored.png';
import _MassiveBraidArmored_webp from './Massive_Braid_Armored.png.webp';
import _MassiveBraidGilded from './Massive_Braid_Gilded.png';
import _MassiveBraidGilded_webp from './Massive_Braid_Gilded.png.webp';
import _MightyPelt from './Mighty_Pelt.png';
import _MightyPelt_webp from './Mighty_Pelt.png.webp';
import _MightyPeltArmored from './Mighty_Pelt_Armored.png';
import _MightyPeltArmored_webp from './Mighty_Pelt_Armored.png.webp';
import _MightyPeltGilded from './Mighty_Pelt_Gilded.png';
import _MightyPeltGilded_webp from './Mighty_Pelt_Gilded.png.webp';
import _MonumentalGoatee from './Monumental_Goatee.png';
import _MonumentalGoatee_webp from './Monumental_Goatee.png.webp';
import _MonumentalGoateeArmored from './Monumental_Goatee_Armored.png';
import _MonumentalGoateeArmored_webp from './Monumental_Goatee_Armored.png.webp';
import _MonumentalGoateeGilded from './Monumental_Goatee_Gilded.png';
import _MonumentalGoateeGilded_webp from './Monumental_Goatee_Gilded.png.webp';
import _NeckGuard from './Neck_Guard.png';
import _NeckGuard_webp from './Neck_Guard.png.webp';
import _PointedNoble from './Pointed_Noble.png';
import _PointedNoble_webp from './Pointed_Noble.png.webp';
import _PositronicNeckbrace from './Positronic_Neckbrace.png';
import _PositronicNeckbrace_webp from './Positronic_Neckbrace.png.webp';
import _RambunctiousElder from './Rambunctious_Elder.png';
import _RambunctiousElder_webp from './Rambunctious_Elder.png.webp';
import _RoundedMuttonchops from './Rounded_Muttonchops.png';
import _RoundedMuttonchops_webp from './Rounded_Muttonchops.png.webp';
import _SavageFull from './Savage_Full.png';
import _SavageFull_webp from './Savage_Full.png.webp';
import _SavageFullArmored from './Savage_Full_Armored.png';
import _SavageFullArmored_webp from './Savage_Full_Armored.png.webp';
import _SavageFullGilded from './Savage_Full_Gilded.png';
import _SavageFullGilded_webp from './Savage_Full_Gilded.png.webp';
import _ScorpionMask from './Scorpion_Mask.png';
import _ScorpionMask_webp from './Scorpion_Mask.png.webp';
import _ShavingAccident from './Shaving_Accident.png';
import _ShavingAccident_webp from './Shaving_Accident.png.webp';
import _ShockTrooper from './Shock_Trooper.png';
import _ShockTrooper_webp from './Shock_Trooper.png.webp';
import _SpaceBiker from './Space_Biker.png';
import _SpaceBiker_webp from './Space_Biker.png.webp';
import _SpikedMohawk from './Spiked_Mohawk.png';
import _SpikedMohawk_webp from './Spiked_Mohawk.png.webp';
import _SpikyNeurotic from './Spiky_Neurotic.png';
import _SpikyNeurotic_webp from './Spiky_Neurotic.png.webp';
import _SwirlyDroop from './Swirly_Droop.png';
import _SwirlyDroop_webp from './Swirly_Droop.png.webp';
import _TankDivision from './Tank_Division.png';
import _TankDivision_webp from './Tank_Division.png.webp';
import _TechEye from './Tech_Eye.png';
import _TechEye_webp from './Tech_Eye.png.webp';
import _TechTrooper from './Tech_Trooper.png';
import _TechTrooper_webp from './Tech_Trooper.png.webp';
import _TechyHardHat from './Techy_Hard_Hat.png';
import _TechyHardHat_webp from './Techy_Hard_Hat.png.webp';
import _TheThickest from './The_Thickest.png';
import _TheThickest_webp from './The_Thickest.png.webp';
import _TripleTrouble from './Triple_Trouble.png';
import _TripleTrouble_webp from './Triple_Trouble.png.webp';
import _TripleTroubleArmored from './Triple_Trouble_Armored.png';
import _TripleTroubleArmored_webp from './Triple_Trouble_Armored.png.webp';
import _TripleTroubleGilded from './Triple_Trouble_Gilded.png';
import _TripleTroubleGilded_webp from './Triple_Trouble_Gilded.png.webp';
import _TwinnedWintry from './Twinned_Wintry.png';
import _TwinnedWintry_webp from './Twinned_Wintry.png.webp';
import _TwinnedWintryArmored from './Twinned_Wintry_Armored.png';
import _TwinnedWintryArmored_webp from './Twinned_Wintry_Armored.png.webp';
import _TwinnedWintryGilded from './Twinned_Wintry_Gilded.png';
import _TwinnedWintryGilded_webp from './Twinned_Wintry_Gilded.png.webp';
import _UpbeatYoungling from './Upbeat_Youngling.png';
import _UpbeatYoungling_webp from './Upbeat_Youngling.png.webp';
import _ValiantBerserker from './Valiant_Berserker.png';
import _ValiantBerserker_webp from './Valiant_Berserker.png.webp';
export const BangledBraids = { png: _BangledBraids, webp: _BangledBraids_webp };
export const Berserker = { png: _Berserker, webp: _Berserker_webp };
export const BigOlSwirls = { png: _BigOlSwirls, webp: _BigOlSwirls_webp };
export const BikerHelmet = { png: _BikerHelmet, webp: _BikerHelmet_webp };
export const BoundBraids = { png: _BoundBraids, webp: _BoundBraids_webp };
export const BoundGoateeArmored = {
  png: _BoundGoateeArmored,
  webp: _BoundGoateeArmored_webp,
};
export const BoundGoateeGilded = {
  png: _BoundGoateeGilded,
  webp: _BoundGoateeGilded_webp,
};
export const BoundGoatee = { png: _BoundGoatee, webp: _BoundGoatee_webp };
export const BoundUnicordArmored = {
  png: _BoundUnicordArmored,
  webp: _BoundUnicordArmored_webp,
};
export const BoundUnicordGilded = {
  png: _BoundUnicordGilded,
  webp: _BoundUnicordGilded_webp,
};
export const BoundUnicord = { png: _BoundUnicord, webp: _BoundUnicord_webp };
export const BraidedAbundanceArmored = {
  png: _BraidedAbundanceArmored,
  webp: _BraidedAbundanceArmored_webp,
};
export const BraidedAbundanceGilded = {
  png: _BraidedAbundanceGilded,
  webp: _BraidedAbundanceGilded_webp,
};
export const BraidedAbundance = {
  png: _BraidedAbundance,
  webp: _BraidedAbundance_webp,
};
export const BraidedBangles = {
  png: _BraidedBangles,
  webp: _BraidedBangles_webp,
};
export const BraidedBoldness = {
  png: _BraidedBoldness,
  webp: _BraidedBoldness_webp,
};
export const BushyGoodGuy = { png: _BushyGoodGuy, webp: _BushyGoodGuy_webp };
export const CategoryBeards = {
  png: _CategoryBeards,
  webp: _CategoryBeards_webp,
};
export const CategoryHeadwear = {
  png: _CategoryHeadwear,
  webp: _CategoryHeadwear_webp,
};
export const CategoryMoustaches = {
  png: _CategoryMoustaches,
  webp: _CategoryMoustaches_webp,
};
export const CategorySideburns = {
  png: _CategorySideburns,
  webp: _CategorySideburns_webp,
};
export const CrescentMoon = { png: _CrescentMoon, webp: _CrescentMoon_webp };
export const CrestedWaterfall = {
  png: _CrestedWaterfall,
  webp: _CrestedWaterfall_webp,
};
export const CurlyOptimist = { png: _CurlyOptimist, webp: _CurlyOptimist_webp };
export const CyborgEye = { png: _CyborgEye, webp: _CyborgEye_webp };
export const DandyHandlebar = {
  png: _DandyHandlebar,
  webp: _DandyHandlebar_webp,
};
export const DoubleHorsetailsArmored = {
  png: _DoubleHorsetailsArmored,
  webp: _DoubleHorsetailsArmored_webp,
};
export const DoubleHorsetailsGilded = {
  png: _DoubleHorsetailsGilded,
  webp: _DoubleHorsetailsGilded_webp,
};
export const DoubleHorsetails = {
  png: _DoubleHorsetails,
  webp: _DoubleHorsetails_webp,
};
export const ExquisiteHandlebar = {
  png: _ExquisiteHandlebar,
  webp: _ExquisiteHandlebar_webp,
};
export const FirstBlood = { png: _FirstBlood, webp: _FirstBlood_webp };
export const ForeheadGoggles = {
  png: _ForeheadGoggles,
  webp: _ForeheadGoggles_webp,
};
export const FullHeadwrap = { png: _FullHeadwrap, webp: _FullHeadwrap_webp };
export const GeekChic = { png: _GeekChic, webp: _GeekChic_webp };
export const GemStuddedHeadcover = {
  png: _GemStuddedHeadcover,
  webp: _GemStuddedHeadcover_webp,
};
export const GoggledHeadwrap = {
  png: _GoggledHeadwrap,
  webp: _GoggledHeadwrap_webp,
};
export const GreatForkArmored = {
  png: _GreatForkArmored,
  webp: _GreatForkArmored_webp,
};
export const GreatForkGilded = {
  png: _GreatForkGilded,
  webp: _GreatForkGilded_webp,
};
export const GreatFork = { png: _GreatFork, webp: _GreatFork_webp };
export const GrimSpecterFullFace = {
  png: _GrimSpecterFullFace,
  webp: _GrimSpecterFullFace_webp,
};
export const GrimSpecterHalfFace = {
  png: _GrimSpecterHalfFace,
  webp: _GrimSpecterHalfFace_webp,
};
export const Heatwave = { png: _Heatwave, webp: _Heatwave_webp };
export const HexHelmet = { png: _HexHelmet, webp: _HexHelmet_webp };
export const HockeyMask = { png: _HockeyMask, webp: _HockeyMask_webp };
export const ImmenseDanglies = {
  png: _ImmenseDanglies,
  webp: _ImmenseDanglies_webp,
};
export const IndustrialFacemask = {
  png: _IndustrialFacemask,
  webp: _IndustrialFacemask_webp,
};
export const IronCyclops = { png: _IronCyclops, webp: _IronCyclops_webp };
export const JovialMajesty = { png: _JovialMajesty, webp: _JovialMajesty_webp };
export const Lowrider = { png: _Lowrider, webp: _Lowrider_webp };
export const MagnificentRaider = {
  png: _MagnificentRaider,
  webp: _MagnificentRaider_webp,
};
export const Marshall = { png: _Marshall, webp: _Marshall_webp };
export const MassiveBraidArmored = {
  png: _MassiveBraidArmored,
  webp: _MassiveBraidArmored_webp,
};
export const MassiveBraidGilded = {
  png: _MassiveBraidGilded,
  webp: _MassiveBraidGilded_webp,
};
export const MassiveBraid = { png: _MassiveBraid, webp: _MassiveBraid_webp };
export const MightyPeltArmored = {
  png: _MightyPeltArmored,
  webp: _MightyPeltArmored_webp,
};
export const MightyPeltGilded = {
  png: _MightyPeltGilded,
  webp: _MightyPeltGilded_webp,
};
export const MightyPelt = { png: _MightyPelt, webp: _MightyPelt_webp };
export const MonumentalGoateeArmored = {
  png: _MonumentalGoateeArmored,
  webp: _MonumentalGoateeArmored_webp,
};
export const MonumentalGoateeGilded = {
  png: _MonumentalGoateeGilded,
  webp: _MonumentalGoateeGilded_webp,
};
export const MonumentalGoatee = {
  png: _MonumentalGoatee,
  webp: _MonumentalGoatee_webp,
};
export const NeckGuard = { png: _NeckGuard, webp: _NeckGuard_webp };
export const PointedNoble = { png: _PointedNoble, webp: _PointedNoble_webp };
export const PositronicNeckbrace = {
  png: _PositronicNeckbrace,
  webp: _PositronicNeckbrace_webp,
};
export const RambunctiousElder = {
  png: _RambunctiousElder,
  webp: _RambunctiousElder_webp,
};
export const RoundedMuttonchops = {
  png: _RoundedMuttonchops,
  webp: _RoundedMuttonchops_webp,
};
export const SavageFullArmored = {
  png: _SavageFullArmored,
  webp: _SavageFullArmored_webp,
};
export const SavageFullGilded = {
  png: _SavageFullGilded,
  webp: _SavageFullGilded_webp,
};
export const SavageFull = { png: _SavageFull, webp: _SavageFull_webp };
export const ScorpionMask = { png: _ScorpionMask, webp: _ScorpionMask_webp };
export const ShavingAccident = {
  png: _ShavingAccident,
  webp: _ShavingAccident_webp,
};
export const ShockTrooper = { png: _ShockTrooper, webp: _ShockTrooper_webp };
export const SpaceBiker = { png: _SpaceBiker, webp: _SpaceBiker_webp };
export const SpikedMohawk = { png: _SpikedMohawk, webp: _SpikedMohawk_webp };
export const SpikyNeurotic = { png: _SpikyNeurotic, webp: _SpikyNeurotic_webp };
export const SwirlyDroop = { png: _SwirlyDroop, webp: _SwirlyDroop_webp };
export const TankDivision = { png: _TankDivision, webp: _TankDivision_webp };
export const TechEye = { png: _TechEye, webp: _TechEye_webp };
export const TechTrooper = { png: _TechTrooper, webp: _TechTrooper_webp };
export const TechyHardHat = { png: _TechyHardHat, webp: _TechyHardHat_webp };
export const TheThickest = { png: _TheThickest, webp: _TheThickest_webp };
export const TripleTroubleArmored = {
  png: _TripleTroubleArmored,
  webp: _TripleTroubleArmored_webp,
};
export const TripleTroubleGilded = {
  png: _TripleTroubleGilded,
  webp: _TripleTroubleGilded_webp,
};
export const TripleTrouble = { png: _TripleTrouble, webp: _TripleTrouble_webp };
export const TwinnedWintryArmored = {
  png: _TwinnedWintryArmored,
  webp: _TwinnedWintryArmored_webp,
};
export const TwinnedWintryGilded = {
  png: _TwinnedWintryGilded,
  webp: _TwinnedWintryGilded_webp,
};
export const TwinnedWintry = { png: _TwinnedWintry, webp: _TwinnedWintry_webp };
export const UpbeatYoungling = {
  png: _UpbeatYoungling,
  webp: _UpbeatYoungling_webp,
};
export const ValiantBerserker = {
  png: _ValiantBerserker,
  webp: _ValiantBerserker_webp,
};
