/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _Balanced from './balanced.png';
import _Balanced_webp from './balanced.png.webp';
import _Clean from './clean.png';
import _Clean_webp from './clean.png.webp';
import _Unstable from './unstable.png';
import _Unstable_webp from './unstable.png.webp';
export const Balanced = { png: _Balanced, webp: _Balanced_webp };
export const Clean = { png: _Clean, webp: _Clean_webp };
export const Unstable = { png: _Unstable, webp: _Unstable_webp };
