/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _CryoCannon from './CryoCannon.png';
import _CryoCannon_webp from './CryoCannon.png.webp';
import _Flamethrower from './Flamethrower.png';
import _Flamethrower_webp from './Flamethrower.png.webp';
import _Subata from './Subata.png';
import _Subata_webp from './Subata.png.webp';
import _Epc from './epc.png';
import _Epc_webp from './epc.png.webp';
export const CryoCannon = { png: _CryoCannon, webp: _CryoCannon_webp };
export const Flamethrower = { png: _Flamethrower, webp: _Flamethrower_webp };
export const Subata = { png: _Subata, webp: _Subata_webp };
export const Epc = { png: _Epc, webp: _Epc_webp };
