/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _BulldogRevolver from './BulldogRevolver.png';
import _BulldogRevolver_webp from './BulldogRevolver.png.webp';
import _BurstFireGun from './BurstFireGun.png';
import _BurstFireGun_webp from './BurstFireGun.png.webp';
import _LeadStormMinigun from './LeadStormMinigun.png';
import _LeadStormMinigun_webp from './LeadStormMinigun.png.webp';
import _ThunderheadAutoCannon from './ThunderheadAutoCannon.png';
import _ThunderheadAutoCannon_webp from './ThunderheadAutoCannon.png.webp';
export const BulldogRevolver = {
  png: _BulldogRevolver,
  webp: _BulldogRevolver_webp,
};
export const BurstFireGun = { png: _BurstFireGun, webp: _BurstFireGun_webp };
export const LeadStormMinigun = {
  png: _LeadStormMinigun,
  webp: _LeadStormMinigun_webp,
};
export const ThunderheadAutoCannon = {
  png: _ThunderheadAutoCannon,
  webp: _ThunderheadAutoCannon_webp,
};
