import { memo } from 'react';

function isPNG(pet: ImgSrc): pet is PNGSrc {
  return (pet as PNGSrc).png !== undefined;
}

/**
 * This Image component allows the app to easily make use of the WebP files
 * generated by the 'update-asset` script whenever possible.
 */
export default memo(function Image(
  props: {
    src: ImgSrc;
    alt: string;
  } & Omit<React.ImgHTMLAttributes<HTMLImageElement>, 'src' | 'alt'>
) {
  const { src, alt, style, ...imgProps } = props;
  return (
    <picture>
      <source type="image/webp" srcSet={src.webp} />
      {isPNG(src) ? (
        <source type="image/png" srcSet={src.png} />
      ) : (
        <source type="image/jpeg" srcSet={src.jpg} />
      )}
      <img
        src={isPNG(src) ? src.png : src.jpg}
        alt={alt}
        style={{ display: 'inline-block', ...style }}
        {...imgProps}
      />
    </picture>
  );
});
