/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _AssaultRifle from './AssaultRifle.png';
import _AssaultRifle_webp from './AssaultRifle.png.webp';
import _Boomstick from './Boomstick.png';
import _Boomstick_webp from './Boomstick.png.webp';
import _M1000 from './M1000.png';
import _M1000_webp from './M1000.png.webp';
import _Zhukov from './Zhukov.png';
import _Zhukov_webp from './Zhukov.png.webp';
export const AssaultRifle = { png: _AssaultRifle, webp: _AssaultRifle_webp };
export const Boomstick = { png: _Boomstick, webp: _Boomstick_webp };
export const M1000 = { png: _M1000, webp: _M1000_webp };
export const Zhukov = { png: _Zhukov, webp: _Zhukov_webp };
