/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _BreachCutter from './BreachCutter.png';
import _BreachCutter_webp from './BreachCutter.png.webp';
import _GrenadeLauncher from './GrenadeLauncher.png';
import _GrenadeLauncher_webp from './GrenadeLauncher.png.webp';
import _Shotgun from './Shotgun.png';
import _Shotgun_webp from './Shotgun.png.webp';
import _StubbySMG from './StubbySMG.png';
import _StubbySMG_webp from './StubbySMG.png.webp';
export const BreachCutter = { png: _BreachCutter, webp: _BreachCutter_webp };
export const GrenadeLauncher = {
  png: _GrenadeLauncher,
  webp: _GrenadeLauncher_webp,
};
export const Shotgun = { png: _Shotgun, webp: _Shotgun_webp };
export const StubbySMG = { png: _StubbySMG, webp: _StubbySMG_webp };
