/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _Autocannon from './Autocannon.png';
import _Autocannon_webp from './Autocannon.png.webp';
import _BurstFireGun from './BurstFireGun.png';
import _BurstFireGun_webp from './BurstFireGun.png.webp';
import _Minigun from './Minigun.png';
import _Minigun_webp from './Minigun.png.webp';
import _Revolver from './Revolver.png';
import _Revolver_webp from './Revolver.png.webp';
export const Autocannon = { png: _Autocannon, webp: _Autocannon_webp };
export const BurstFireGun = { png: _BurstFireGun, webp: _BurstFireGun_webp };
export const Minigun = { png: _Minigun, webp: _Minigun_webp };
export const Revolver = { png: _Revolver, webp: _Revolver_webp };
