#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SRC_DIR="$DIR/../src"

function generate_index {
  local pngs=()
  local jpgs=()
  local directories=()

  for file in $1/*; do
    if [[ $file == *.png ]]; then
      pngs+=( ${file#"$1/"} )
    elif [[ $file == *.jpg ]]; then
      jpgs+=( ${file#"$1/"} )
    elif [ -d $file ]; then
      yarn webpconvert $file
      directories+=( ${file#"$1/"} )
      generate_index $file
    fi
  done

  if [ ${#pngs[@]} -eq 0 ] && \
     [ ${#jpgs[@]} -eq 0 ] && \
     [ ${#directories[@]} -eq 0 ]
  then
    return
  fi

  local imports=()
  local exports=()

  # PNGs
  for image in "${pngs[@]}"; do
    local name=${image%".png"}
    name=$(echo $name | sed -E 's/_(.)/\U\1/g')
    name=${name^}
    imports+=( "import _$name from './$image';" )
    imports+=( "import _${name}_webp from './$image.webp';" )
    exports+=( "export const $name = { png: _$name, webp: _${name}_webp };" )
  done

  # JPGs
  for image in "${jpgs[@]}"; do
    local name=${image%".jpg"}
    name=$(echo $name | sed -E 's/_(.)/\U\1/g')
    name=${name^}
    imports+=( "import _$name from './$image';" )
    imports+=( "import _${name}_webp from './$image.webp';" )
    exports+=( "export const $name = { jpg: _$name, webp: _${name}_webp };" )
  done

  # Subdirectories
  for directory in "${directories[@]}"; do
    imports+=( "import * as $directory from './$directory';" )
  done
  if [[ ${directories[@]} ]]; then
    local dir_import_string=$(IFS=,;printf  "%s" "${directories[*]}")
    exports+=( "const _imports = { $dir_import_string };" )
    exports+=( "export default _imports;" )
  fi

  local export_string=""
  imports+=( "${exports[@]}" )
  printf -v export_string "%s\n" "${imports[@]}"

  cat << EOF > $1/index.ts
/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run \`yarn update-assets\` in the project root.
 */

$export_string
EOF

  truncate -s -1 "$1/index.ts"
}

for file in $SRC_DIR/assets/*; do
  if [ -d $file ]; then
    yarn webpconvert $(realpath $file)
    generate_index $(realpath $file)
  fi
done