/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _Crossbow from './Crossbow.png';
import _Crossbow_webp from './Crossbow.png.webp';
import _DeepcoreAssaultRifle from './DeepcoreAssaultRifle.png';
import _DeepcoreAssaultRifle_webp from './DeepcoreAssaultRifle.png.webp';
import _M1000SniperRifle from './M1000SniperRifle.png';
import _M1000SniperRifle_webp from './M1000SniperRifle.png.webp';
import _PlasmaCarbine from './PlasmaCarbine.png';
import _PlasmaCarbine_webp from './PlasmaCarbine.png.webp';
import _SawedOffShotgun from './SawedOffShotgun.png';
import _SawedOffShotgun_webp from './SawedOffShotgun.png.webp';
import _ZhukovMachinePistols from './ZhukovMachinePistols.png';
import _ZhukovMachinePistols_webp from './ZhukovMachinePistols.png.webp';
export const Crossbow = { png: _Crossbow, webp: _Crossbow_webp };
export const DeepcoreAssaultRifle = {
  png: _DeepcoreAssaultRifle,
  webp: _DeepcoreAssaultRifle_webp,
};
export const M1000SniperRifle = {
  png: _M1000SniperRifle,
  webp: _M1000SniperRifle_webp,
};
export const PlasmaCarbine = { png: _PlasmaCarbine, webp: _PlasmaCarbine_webp };
export const SawedOffShotgun = {
  png: _SawedOffShotgun,
  webp: _SawedOffShotgun_webp,
};
export const ZhukovMachinePistols = {
  png: _ZhukovMachinePistols,
  webp: _ZhukovMachinePistols_webp,
};
