/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _Chalkbuster from './Chalkbuster.png';
import _Chalkbuster_webp from './Chalkbuster.png.webp';
import _ChocolateReign from './Chocolate_Reign.png';
import _ChocolateReign_webp from './Chocolate_Reign.png.webp';
import _Colossus from './Colossus.png';
import _Colossus_webp from './Colossus.png.webp';
import _DDarkFuture from './D_Dark_Future.png';
import _DDarkFuture_webp from './D_Dark_Future.png.webp';
import _DDefaultPaintjob from './D_Default_Paintjob.png';
import _DDefaultPaintjob_webp from './D_Default_Paintjob.png.webp';
import _DSplattered from './D_Splattered.png';
import _DSplattered_webp from './D_Splattered.png.webp';
import _DTheSupporter from './D_The_Supporter.png';
import _DTheSupporter_webp from './D_The_Supporter.png.webp';
import _IntricateCarver from './Intricate_Carver.png';
import _IntricateCarver_webp from './Intricate_Carver.png.webp';
import _MudRunner from './Mud_Runner.png';
import _MudRunner_webp from './Mud_Runner.png.webp';
import _MuddyPath from './Muddy_Path.png';
import _MuddyPath_webp from './Muddy_Path.png.webp';
export const Chalkbuster = { png: _Chalkbuster, webp: _Chalkbuster_webp };
export const ChocolateReign = {
  png: _ChocolateReign,
  webp: _ChocolateReign_webp,
};
export const Colossus = { png: _Colossus, webp: _Colossus_webp };
export const DDarkFuture = { png: _DDarkFuture, webp: _DDarkFuture_webp };
export const DDefaultPaintjob = {
  png: _DDefaultPaintjob,
  webp: _DDefaultPaintjob_webp,
};
export const DSplattered = { png: _DSplattered, webp: _DSplattered_webp };
export const DTheSupporter = { png: _DTheSupporter, webp: _DTheSupporter_webp };
export const IntricateCarver = {
  png: _IntricateCarver,
  webp: _IntricateCarver_webp,
};
export const MudRunner = { png: _MudRunner, webp: _MudRunner_webp };
export const MuddyPath = { png: _MuddyPath, webp: _MuddyPath_webp };
