/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _ChopChop from './chopChop.jpg';
import _ChopChop_webp from './chopChop.jpg.webp';
import _HoleDigger from './holeDigger.jpg';
import _HoleDigger_webp from './holeDigger.jpg.webp';
import _ObsidianMallet from './obsidianMallet.jpg';
import _ObsidianMallet_webp from './obsidianMallet.jpg.webp';
import _SkullBuster from './skullBuster.jpg';
import _SkullBuster_webp from './skullBuster.jpg.webp';
export const ChopChop = { jpg: _ChopChop, webp: _ChopChop_webp };
export const HoleDigger = { jpg: _HoleDigger, webp: _HoleDigger_webp };
export const ObsidianMallet = {
  jpg: _ObsidianMallet,
  webp: _ObsidianMallet_webp,
};
export const SkullBuster = { jpg: _SkullBuster, webp: _SkullBuster_webp };
