/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _Dustrunner from './Dustrunner.png';
import _Dustrunner_webp from './Dustrunner.png.webp';
import _EDarkFuture from './E_Dark_Future.png';
import _EDarkFuture_webp from './E_Dark_Future.png.webp';
import _EDefaultPaintjob from './E_Default_Paintjob.png';
import _EDefaultPaintjob_webp from './E_Default_Paintjob.png.webp';
import _ESplattered from './E_Splattered.png';
import _ESplattered_webp from './E_Splattered.png.webp';
import _ETheSupporter from './E_The_Supporter.png';
import _ETheSupporter_webp from './E_The_Supporter.png.webp';
import _EmberFury from './Ember_Fury.png';
import _EmberFury_webp from './Ember_Fury.png.webp';
import _GrungeBuster from './Grunge_Buster.png';
import _GrungeBuster_webp from './Grunge_Buster.png.webp';
import _OrangeGeek from './Orange_Geek.png';
import _OrangeGeek_webp from './Orange_Geek.png.webp';
import _TeacherPet from './Teacher_Pet.png';
import _TeacherPet_webp from './Teacher_Pet.png.webp';
import _TopDog from './Top_Dog.png';
import _TopDog_webp from './Top_Dog.png.webp';
export const Dustrunner = { png: _Dustrunner, webp: _Dustrunner_webp };
export const EDarkFuture = { png: _EDarkFuture, webp: _EDarkFuture_webp };
export const EDefaultPaintjob = {
  png: _EDefaultPaintjob,
  webp: _EDefaultPaintjob_webp,
};
export const ESplattered = { png: _ESplattered, webp: _ESplattered_webp };
export const ETheSupporter = { png: _ETheSupporter, webp: _ETheSupporter_webp };
export const EmberFury = { png: _EmberFury, webp: _EmberFury_webp };
export const GrungeBuster = { png: _GrungeBuster, webp: _GrungeBuster_webp };
export const OrangeGeek = { png: _OrangeGeek, webp: _OrangeGeek_webp };
export const TeacherPet = { png: _TeacherPet, webp: _TeacherPet_webp };
export const TopDog = { png: _TopDog, webp: _TopDog_webp };
