/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _CryoCannon from './CryoCannon.png';
import _CryoCannon_webp from './CryoCannon.png.webp';
import _ExperimentalPlasmaCharger from './ExperimentalPlasmaCharger.png';
import _ExperimentalPlasmaCharger_webp from './ExperimentalPlasmaCharger.png.webp';
import _FlameThrower from './FlameThrower.png';
import _FlameThrower_webp from './FlameThrower.png.webp';
import _Subata120 from './Subata120.png';
import _Subata120_webp from './Subata120.png.webp';
export const CryoCannon = { png: _CryoCannon, webp: _CryoCannon_webp };
export const ExperimentalPlasmaCharger = {
  png: _ExperimentalPlasmaCharger,
  webp: _ExperimentalPlasmaCharger_webp,
};
export const FlameThrower = { png: _FlameThrower, webp: _FlameThrower_webp };
export const Subata120 = { png: _Subata120, webp: _Subata120_webp };
