/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _AccessoryIcon from './accessoryIcon.png';
import _AccessoryIcon_webp from './accessoryIcon.png.webp';
import _Assignment from './assignment.png';
import _Assignment_webp from './assignment.png.webp';
import _ForgeHammer from './forgeHammer.png';
import _ForgeHammer_webp from './forgeHammer.png.webp';
import _ForgeMastery from './forgeMastery.png';
import _ForgeMastery_webp from './forgeMastery.png.webp';
import _LostPack from './lostPack.png';
import _LostPack_webp from './lostPack.png.webp';
import _PaintPickaxeIcon from './paintPickaxeIcon.png';
import _PaintPickaxeIcon_webp from './paintPickaxeIcon.png.webp';
import _PerkStar from './perkStar.png';
import _PerkStar_webp from './perkStar.png.webp';
import _PickaxeIcon from './pickaxeIcon.png';
import _PickaxeIcon_webp from './pickaxeIcon.png.webp';
import _PlayerRankIcon from './playerRankIcon.png';
import _PlayerRankIcon_webp from './playerRankIcon.png.webp';
import _RockAndStone from './rockAndStone.png';
import _RockAndStone_webp from './rockAndStone.png.webp';
import _SatchelCharge from './satchelCharge.png';
import _SatchelCharge_webp from './satchelCharge.png.webp';
export const AccessoryIcon = { png: _AccessoryIcon, webp: _AccessoryIcon_webp };
export const Assignment = { png: _Assignment, webp: _Assignment_webp };
export const ForgeHammer = { png: _ForgeHammer, webp: _ForgeHammer_webp };
export const ForgeMastery = { png: _ForgeMastery, webp: _ForgeMastery_webp };
export const LostPack = { png: _LostPack, webp: _LostPack_webp };
export const PaintPickaxeIcon = {
  png: _PaintPickaxeIcon,
  webp: _PaintPickaxeIcon_webp,
};
export const PerkStar = { png: _PerkStar, webp: _PerkStar_webp };
export const PickaxeIcon = { png: _PickaxeIcon, webp: _PickaxeIcon_webp };
export const PlayerRankIcon = {
  png: _PlayerRankIcon,
  webp: _PlayerRankIcon_webp,
};
export const RockAndStone = { png: _RockAndStone, webp: _RockAndStone_webp };
export const SatchelCharge = { png: _SatchelCharge, webp: _SatchelCharge_webp };
