const icons = <M extends { [k: string]: Promise<typeof import("*.png")> }>(
  things: M
) => things;

export default icons({
  aim: import("./aim.png"),
  ammo: import("./ammo.png"),
  area: import("./area.png"),
  areaDamage: import("./areaDamage.png"),
  chance: import("./chance.png"),
  chargeUp: import("./chargeUp.png"),
  clipSize: import("./clipSize.png"),
  cold: import("./cold.png"),
  cooldown: import("./cooldown.png"),
  damage: import("./damage.png"),
  distance: import("./distance.png"),
  duration: import("./duration.png"),
  durationHourglass: import("./durationHourglass.png"),
  electricity: import("./electricity.png"),
  explosion: import("./explosion.png"),
  explosionJump: import("./explosionJump.png"),
  fireRate: import("./fireRate.png"),
  forthAndBackLinecutter: import("./forthAndBackLinecutter.png"),
  fuel: import("./fuel.png"),
  heat: import("./heat.png"),
  movementSpeed: import("./movementSpeed.png"),
  neuro: import("./neuro.png"),
  projectileSpeed: import("./projectileSpeed.png"),
  reloadSpeed: import("./reloadSpeed.png"),
  ricochet: import("./ricochet.png"),
  shotgunJump: import("./shotgunJump.png"),
  shotgunPellet: import("./shotgunPellet.png"),
  slowdown: import("./slowdown.png"),
  smallBullets: import("./smallBullets.png"),
  special: import("./special.png"),
  specialMagazine: import("./specialMagazine.png"),
  spinningLinecutter: import("./spinningLinecutter.png"),
  stun: import("./stun.png"),
});
