/**
 * This index file is generated by generate_asset_wrappers.sh.
 * To update it, run `yarn update-assets` in the project root.
 */

import _Aim from './aim.png';
import _Aim_webp from './aim.png.webp';
import _Ammo from './ammo.png';
import _Ammo_webp from './ammo.png.webp';
import _Area from './area.png';
import _Area_webp from './area.png.webp';
import _AreaDamage from './areaDamage.png';
import _AreaDamage_webp from './areaDamage.png.webp';
import _Chance from './chance.png';
import _Chance_webp from './chance.png.webp';
import _ChargeUp from './chargeUp.png';
import _ChargeUp_webp from './chargeUp.png.webp';
import _ClipSize from './clipSize.png';
import _ClipSize_webp from './clipSize.png.webp';
import _Cold from './cold.png';
import _Cold_webp from './cold.png.webp';
import _Cooldown from './cooldown.png';
import _Cooldown_webp from './cooldown.png.webp';
import _Damage from './damage.png';
import _Damage_webp from './damage.png.webp';
import _Distance from './distance.png';
import _Distance_webp from './distance.png.webp';
import _Duration from './duration.png';
import _Duration_webp from './duration.png.webp';
import _DurationHourglass from './durationHourglass.png';
import _DurationHourglass_webp from './durationHourglass.png.webp';
import _Electricity from './electricity.png';
import _Electricity_webp from './electricity.png.webp';
import _Explosion from './explosion.png';
import _Explosion_webp from './explosion.png.webp';
import _ExplosionJump from './explosionJump.png';
import _ExplosionJump_webp from './explosionJump.png.webp';
import _FireRate from './fireRate.png';
import _FireRate_webp from './fireRate.png.webp';
import _ForthAndBackLinecutter from './forthAndBackLinecutter.png';
import _ForthAndBackLinecutter_webp from './forthAndBackLinecutter.png.webp';
import _Fuel from './fuel.png';
import _Fuel_webp from './fuel.png.webp';
import _Heat from './heat.png';
import _Heat_webp from './heat.png.webp';
import _MovementSpeed from './movementSpeed.png';
import _MovementSpeed_webp from './movementSpeed.png.webp';
import _Neuro from './neuro.png';
import _Neuro_webp from './neuro.png.webp';
import _ProjectileSpeed from './projectileSpeed.png';
import _ProjectileSpeed_webp from './projectileSpeed.png.webp';
import _ReloadSpeed from './reloadSpeed.png';
import _ReloadSpeed_webp from './reloadSpeed.png.webp';
import _Ricochet from './ricochet.png';
import _Ricochet_webp from './ricochet.png.webp';
import _ShotgunJump from './shotgunJump.png';
import _ShotgunJump_webp from './shotgunJump.png.webp';
import _ShotgunPellet from './shotgunPellet.png';
import _ShotgunPellet_webp from './shotgunPellet.png.webp';
import _Slowdown from './slowdown.png';
import _Slowdown_webp from './slowdown.png.webp';
import _SmallBullets from './smallBullets.png';
import _SmallBullets_webp from './smallBullets.png.webp';
import _Special from './special.png';
import _Special_webp from './special.png.webp';
import _SpecialMagazine from './specialMagazine.png';
import _SpecialMagazine_webp from './specialMagazine.png.webp';
import _SpinningLinecutter from './spinningLinecutter.png';
import _SpinningLinecutter_webp from './spinningLinecutter.png.webp';
import _Stun from './stun.png';
import _Stun_webp from './stun.png.webp';
export const Aim = { png: _Aim, webp: _Aim_webp };
export const Ammo = { png: _Ammo, webp: _Ammo_webp };
export const Area = { png: _Area, webp: _Area_webp };
export const AreaDamage = { png: _AreaDamage, webp: _AreaDamage_webp };
export const Chance = { png: _Chance, webp: _Chance_webp };
export const ChargeUp = { png: _ChargeUp, webp: _ChargeUp_webp };
export const ClipSize = { png: _ClipSize, webp: _ClipSize_webp };
export const Cold = { png: _Cold, webp: _Cold_webp };
export const Cooldown = { png: _Cooldown, webp: _Cooldown_webp };
export const Damage = { png: _Damage, webp: _Damage_webp };
export const Distance = { png: _Distance, webp: _Distance_webp };
export const Duration = { png: _Duration, webp: _Duration_webp };
export const DurationHourglass = {
  png: _DurationHourglass,
  webp: _DurationHourglass_webp,
};
export const Electricity = { png: _Electricity, webp: _Electricity_webp };
export const Explosion = { png: _Explosion, webp: _Explosion_webp };
export const ExplosionJump = { png: _ExplosionJump, webp: _ExplosionJump_webp };
export const FireRate = { png: _FireRate, webp: _FireRate_webp };
export const ForthAndBackLinecutter = {
  png: _ForthAndBackLinecutter,
  webp: _ForthAndBackLinecutter_webp,
};
export const Fuel = { png: _Fuel, webp: _Fuel_webp };
export const Heat = { png: _Heat, webp: _Heat_webp };
export const MovementSpeed = { png: _MovementSpeed, webp: _MovementSpeed_webp };
export const Neuro = { png: _Neuro, webp: _Neuro_webp };
export const ProjectileSpeed = {
  png: _ProjectileSpeed,
  webp: _ProjectileSpeed_webp,
};
export const ReloadSpeed = { png: _ReloadSpeed, webp: _ReloadSpeed_webp };
export const Ricochet = { png: _Ricochet, webp: _Ricochet_webp };
export const ShotgunJump = { png: _ShotgunJump, webp: _ShotgunJump_webp };
export const ShotgunPellet = { png: _ShotgunPellet, webp: _ShotgunPellet_webp };
export const Slowdown = { png: _Slowdown, webp: _Slowdown_webp };
export const SmallBullets = { png: _SmallBullets, webp: _SmallBullets_webp };
export const Special = { png: _Special, webp: _Special_webp };
export const SpecialMagazine = {
  png: _SpecialMagazine,
  webp: _SpecialMagazine_webp,
};
export const SpinningLinecutter = {
  png: _SpinningLinecutter,
  webp: _SpinningLinecutter_webp,
};
export const Stun = { png: _Stun, webp: _Stun_webp };
